highlight ranges
Notist/api pull request #14
Opened 2017-03-21 22:59 UTC by psloomis

## Why
These changes allow for highlighting article annotations in the browser extension - see https://github.com/Notist/browser-extension/pull/5 which implements highlighting. Annotation objects must keep track of the selected DOM that corresponds the annotation's articleText. This way, we know which parts of the DOM to highlight on the frontend.
This PR makes each annotation store a `ranges` field, which indicates which part of the article's DOM to highlight in order to highlight the an annotation's article text.
e.g. A ranges field might look like this:
```
  ranges: [
    {
      start: "/p[69]/span/span",           # to start element
      end: "/p[70]/span/span",             # end element
      startOffset: 0,                      # character offset within start element
      endOffset: 120                       # character offset within end element
    }
  ]
```
And, on the frontend, we highlight the ranges to make the article text appear highlighted.

## Changes
- Added a `ranges` field to the `Annotation` schema
- Changed the `createAnnotation` method to accept the range field for top-level annotations

2017-03-24 22:19 UTC, psloomis commented
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate Annotator - http://annotatorjs.org/ - with browser extension to allow highlighting on page](https://trello.com/c/VcMak841/2-integrate-annotator-http-annotatorjs-org-with-browser-extension-to-allow-highlighting-on-page)

2017-03-25 18:16 UTC, ethanbb requested changes

2017-03-25 18:16 UTC, ethanbb commented on server/controllers/annotation_controller.js
>    } else {
Should we also give each child annotation a ranges field, which would have the same value as its parent's? Or did you only want to store this for top-level annotations?

If we are never planning to access an annotation without also showing all of its ancestors along with the article text, then I guess it makes sense to only store the ranges in the top annotation.

2017-03-25 18:16 UTC, ethanbb commented on server/models/annotation.js
> +  ranges: { type: Array, default: [] },
We should be able to specify this part of the schema more specifically (assuming each member of the array should have the same format). I can change this and make a commit.

2017-03-25 20:22 UTC, psloomis commented on server/controllers/annotation_controller.js
>    } else {
We only want to store the ranges field for top-level annotations.

2017-03-25 20:34 UTC, psloomis commented on server/models/annotation.js
> +  ranges: { type: Array, default: [] },
Yes, it should be more specific. Maybe something like this?
```
ranges: [
  {
    start: { type: String },
    end: { type: String },
    startOffset: { type: Number },
    endOffset: { type: Number },
  }
]
```

2017-03-25 22:05 UTC, ethanbb commented
Wait that's weird, all my tests passed...hold on

2017-03-25 23:38 UTC, ethanbb approved these changes

2017-03-28 14:56 UTC, merged